### ISSUE TITLE
 libevent_core-2.1.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WalkOnMars** [liuwenru/intelliq-redsocks#5]
start the redsocks........................
please tell me you sock_server:127.0.0.1
please tell me you sock_port:7070
./redsocks: error while loading shared libraries: libevent_core-2.1.so.6: cannot open shared object file: No such file or directory
(base) [root@localhost intelliq-redsocks]# ^C
(base) [root@localhost intelliq-redsocks]#

**Comment by gqbre** [comment]
same problem.
libevent - 2.0.20-1 - /opt/lib/libevent_core-2.0.so.5

**Comment by liuwenru** [comment]
你这个问题需要安装yum install libevent-devel 然后，重新编译redsockes就可以了，我提交的版本比较老
